### PR TITLE
Update Twitter Icon to New X Icon

### PR DESCRIPTION
**Pull request by BishalJena**
This pull request addresses issue #18, which involves updating the old Twitter bird icon to the new “X” icon. The following changes have been made:

	•	Replaced the SVG path data in the TwitterIcon component with the new “X” logo.
	•	Updated relevant component and file names to reflect the change from “Twitter” to “X,” where applicable.

This change is part of the rebranding from Twitter to X and ensures that all visual representations align with the new branding guidelines.
Fixes: #18

### CODE REVIEW

**Comment by BishalJena** [comment]
@ibgreen @chrisgervang kindly check this PR and merge if passes the checks.

**Comment by ibgreen** [comment]
@BishalJena Thanks for the PR. Not sure I have the authority to authorize the Vercel deployment though.

**Comment by BishalJena** [comment]
@ibgreen can you ping other maintainers who'd have the vercel authorization? i couldn't anyone else active except you.

**Review by chrisgervang — APPROVED** [review]

**Comment by BishalJena** [comment]
@chrisgervang as you reviewed the changes, can you authorize vercel and merge this PR?

**Comment by chrisgervang** [comment]
Hey @BishalJena, I have permission to merge this but I'm not familiar with the deployment system and ran into an issue.

Any particular reason to close this?

**Comment by AryanVBW** [comment]
@chrisgervang I’ve submitted the same pull request with the requested changes. Please check it out and let me know if you have any suggestions. I'll be happy to make updates!
https://github.com/openjs-foundation/open-visualization/pull/22

**Pull request closed without merging**
